version: '3'

services:
  traefik:
    image: traefik:v1.7-alpine
    restart: always
    command: --api --docker
    ports:
        - "80:80"
        - "443:443"
        - "127.0.0.1:8080:8080" # The Web UI (enabled by --api)
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik/traefik.toml:/traefik.toml
        - ./traefik/acme.json:/acme.json
    container_name: "traefik"
    networks:
    - traefik

  watchtower:
    image: v2tec/watchtower
    restart: always
    container_name: "portainer-watchtower"
    command: --cleanup turniere-frontend turniere-backend traefik 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

  frontend:
    image: 
    restart: always
    container_name: "turniere-frontend"
    env_file:
      - 'turniere-frontend.env'
    labels:
      - "traefik.frontend.rule=Host:your.domain.here" # Enter your frontend domain here
      - "traefik.port=80"
      - "traefik.docker.network=traefik"
    networks:
      - traefik

  backend:
    image: 
    restart: always
    container_name: "turniere-backend"
    env_file:
      - 'turniere-backend.env'
    labels:
      - "traefik.frontend.rule=Host:your.domain.here" # Enter your backend domain here
      - "traefik.port=3000"
      - "traefik.docker.network=traefik"
    networks:
      - traefik

networks:
  traefik:
    driver: bridge
